[project]
name="lua"
version="5-5-1"
kmake="project.kmake"

[references]

[windows-sync]
lua_copy_src_onelua=[ "../onelua.c", "src/onelua.c", "copy" ]
lua_copy_src_lzio=[ "../lzio.c", "src/lzio.c", "copy" ]
lua_copy_src_lvm=[ "../lvm.c", "src/lvm.c", "copy" ]
lua_copy_src_lutf8lib=[ "../lutf8lib.c", "src/lutf8lib.c", "copy" ]
lua_copy_src_lundump=[ "../lundump.c", "src/lundump.c", "copy" ]
lua_copy_src_lua=[ "../lua.c", "src/lua.c", "copy" ]
lua_copy_src_ltm=[ "../ltm.c", "src/ltm.c", "copy" ]
lua_copy_src_ltests=[ "../ltests.c", "src/ltests.c", "copy" ]
lua_copy_src_ltablib=[ "../ltablib.c", "src/ltablib.c", "copy" ]
lua_copy_src_ltable=[ "../ltable.c", "src/ltable.c", "copy" ]
lua_copy_src_lstrlib=[ "../lstrlib.c", "src/lstrlib.c", "copy" ]
lua_copy_src_lstring=[ "../lstring.c", "src/lstring.c", "copy" ]
lua_copy_src_lstate=[ "../lstate.c", "src/lstate.c", "copy" ]
lua_copy_src_lparser=[ "../lparser.c", "src/lparser.c", "copy" ]
lua_copy_src_loslib=[ "../loslib.c", "src/loslib.c", "copy" ]
lua_copy_src_lopcodes=[ "../lopcodes.c", "src/lopcodes.c", "copy" ]
lua_copy_src_lobject=[ "../lobject.c", "src/lobject.c", "copy" ]
lua_copy_src_loadlib=[ "../loadlib.c", "src/loadlib.c", "copy" ]
lua_copy_src_lmem=[ "../lmem.c", "src/lmem.c", "copy" ]
lua_copy_src_lmathlib=[ "../lmathlib.c", "src/lmathlib.c", "copy" ]
lua_copy_src_llex=[ "../llex.c", "src/llex.c", "copy" ]
lua_copy_src_liolib=[ "../liolib.c", "src/liolib.c", "copy" ]
lua_copy_src_linit=[ "../linit.c", "src/linit.c", "copy" ]
lua_copy_src_lgc=[ "../lgc.c", "src/lgc.c", "copy" ]
lua_copy_src_lfunc=[ "../lfunc.c", "src/lfunc.c", "copy" ]
lua_copy_src_ldump=[ "../ldump.c", "src/ldump.c", "copy" ]
lua_copy_src_ldo=[ "../ldo.c", "src/ldo.c", "copy" ]
lua_copy_src_ldebug=[ "../ldebug.c", "src/ldebug.c", "copy" ]
lua_copy_src_ldblib=[ "../ldblib.c", "src/ldblib.c", "copy" ]
lua_copy_src_lctype=[ "../lctype.c", "src/lctype.c", "copy" ]
lua_copy_src_lcorolib=[ "../lcorolib.c", "src/lcorolib.c", "copy" ]
lua_copy_src_lcode=[ "../lcode.c", "src/lcode.c", "copy" ]
lua_copy_src_lbaselib=[ "../lbaselib.c", "src/lbaselib.c", "copy" ]
lua_copy_src_lauxlib=[ "../lauxlib.c", "src/lauxlib.c", "copy" ]
lua_copy_src_lapi=[ "../lapi.c", "src/lapi.c", "copy" ]
lua_copy_inc_lzio=[ "../lzio.h", "include/lzio.h", "copy" ]
lua_copy_inc_lvm=[ "../lvm.h", "include/lvm.h", "copy" ]
lua_copy_inc_lundump=[ "../lundump.h", "include/lundump.h", "copy" ]
lua_copy_inc_lualib=[ "../lualib.h", "include/lualib.h", "copy" ]
lua_copy_inc_luaconf=[ "../luaconf.h", "include/luaconf.h", "copy" ]
lua_copy_inc_lua=[ "../lua.h", "include/lua.h", "copy" ]
lua_copy_inc_ltm=[ "../ltm.h", "include/ltm.h", "copy" ]
lua_copy_inc_ltests=[ "../ltests.h", "include/ltests.h", "copy" ]
lua_copy_inc_ltable=[ "../ltable.h", "include/ltable.h", "copy" ]
lua_copy_inc_lstring=[ "../lstring.h", "include/lstring.h", "copy" ]
lua_copy_inc_lstate=[ "../lstate.h", "include/lstate.h", "copy" ]
lua_copy_inc_lprefix=[ "../lprefix.h", "include/lprefix.h", "copy" ]
lua_copy_inc_lparser=[ "../lparser.h", "include/lparser.h", "copy" ]
lua_copy_inc_lopnames=[ "../lopnames.h", "include/lopnames.h", "copy" ]
lua_copy_inc_lopcodes=[ "../lopcodes.h", "include/lopcodes.h", "copy" ]
lua_copy_inc_lobject=[ "../lobject.h", "include/lobject.h", "copy" ]
lua_copy_inc_lmem=[ "../lmem.h", "include/lmem.h", "copy" ]
lua_copy_inc_llimits=[ "../llimits.h", "include/llimits.h", "copy" ]
lua_copy_inc_llex=[ "../llex.h", "include/llex.h", "copy" ]
lua_copy_inc_ljumptab=[ "../ljumptab.h", "include/ljumptab.h", "copy" ]
lua_copy_inc_lgc=[ "../lgc.h", "include/lgc.h", "copy" ]
lua_copy_inc_lfunc=[ "../lfunc.h", "include/lfunc.h", "copy" ]
lua_copy_inc_ldo=[ "../ldo.h", "include/ldo.h", "copy" ]
lua_copy_inc_ldebug=[ "../ldebug.h", "include/ldebug.h", "copy" ]
lua_copy_inc_lctype=[ "../lctype.h", "include/lctype.h", "copy" ]
lua_copy_inc_lcode=[ "../lcode.h", "include/lcode.h", "copy" ]
lua_copy_inc_lauxlib=[ "../lauxlib.h", "include/lauxlib.h", "copy" ]
lua_copy_inc_lapi=[ "../lapi.h", "include/lapi.h", "copy" ]

[windows-post-build-sync]
lo_bin_rel=[ "build/temp/release-windows/lua.lib", "build/${version}/lua.lib", "copy" ]
lo_bin_deb=[ "build/temp/debug-windows/luad.lib", "build/${version}/luad.lib", "copy" ]
lo_include=[ "include", "build/${version}/include", "copy" ]
lo_license=[ "LICENSE", "build/${version}/LICENSE", "copy" ]

[windows-gnu-sync]
lua_copy_src_onelua=[ "../onelua.c", "src/onelua.c", "copy" ]
lua_copy_src_lzio=[ "../lzio.c", "src/lzio.c", "copy" ]
lua_copy_src_lvm=[ "../lvm.c", "src/lvm.c", "copy" ]
lua_copy_src_lutf8lib=[ "../lutf8lib.c", "src/lutf8lib.c", "copy" ]
lua_copy_src_lundump=[ "../lundump.c", "src/lundump.c", "copy" ]
lua_copy_src_lua=[ "../lua.c", "src/lua.c", "copy" ]
lua_copy_src_ltm=[ "../ltm.c", "src/ltm.c", "copy" ]
lua_copy_src_ltests=[ "../ltests.c", "src/ltests.c", "copy" ]
lua_copy_src_ltablib=[ "../ltablib.c", "src/ltablib.c", "copy" ]
lua_copy_src_ltable=[ "../ltable.c", "src/ltable.c", "copy" ]
lua_copy_src_lstrlib=[ "../lstrlib.c", "src/lstrlib.c", "copy" ]
lua_copy_src_lstring=[ "../lstring.c", "src/lstring.c", "copy" ]
lua_copy_src_lstate=[ "../lstate.c", "src/lstate.c", "copy" ]
lua_copy_src_lparser=[ "../lparser.c", "src/lparser.c", "copy" ]
lua_copy_src_loslib=[ "../loslib.c", "src/loslib.c", "copy" ]
lua_copy_src_lopcodes=[ "../lopcodes.c", "src/lopcodes.c", "copy" ]
lua_copy_src_lobject=[ "../lobject.c", "src/lobject.c", "copy" ]
lua_copy_src_loadlib=[ "../loadlib.c", "src/loadlib.c", "copy" ]
lua_copy_src_lmem=[ "../lmem.c", "src/lmem.c", "copy" ]
lua_copy_src_lmathlib=[ "../lmathlib.c", "src/lmathlib.c", "copy" ]
lua_copy_src_llex=[ "../llex.c", "src/llex.c", "copy" ]
lua_copy_src_liolib=[ "../liolib.c", "src/liolib.c", "copy" ]
lua_copy_src_linit=[ "../linit.c", "src/linit.c", "copy" ]
lua_copy_src_lgc=[ "../lgc.c", "src/lgc.c", "copy" ]
lua_copy_src_lfunc=[ "../lfunc.c", "src/lfunc.c", "copy" ]
lua_copy_src_ldump=[ "../ldump.c", "src/ldump.c", "copy" ]
lua_copy_src_ldo=[ "../ldo.c", "src/ldo.c", "copy" ]
lua_copy_src_ldebug=[ "../ldebug.c", "src/ldebug.c", "copy" ]
lua_copy_src_ldblib=[ "../ldblib.c", "src/ldblib.c", "copy" ]
lua_copy_src_lctype=[ "../lctype.c", "src/lctype.c", "copy" ]
lua_copy_src_lcorolib=[ "../lcorolib.c", "src/lcorolib.c", "copy" ]
lua_copy_src_lcode=[ "../lcode.c", "src/lcode.c", "copy" ]
lua_copy_src_lbaselib=[ "../lbaselib.c", "src/lbaselib.c", "copy" ]
lua_copy_src_lauxlib=[ "../lauxlib.c", "src/lauxlib.c", "copy" ]
lua_copy_src_lapi=[ "../lapi.c", "src/lapi.c", "copy" ]
lua_copy_inc_lzio=[ "../lzio.h", "include/lzio.h", "copy" ]
lua_copy_inc_lvm=[ "../lvm.h", "include/lvm.h", "copy" ]
lua_copy_inc_lundump=[ "../lundump.h", "include/lundump.h", "copy" ]
lua_copy_inc_lualib=[ "../lualib.h", "include/lualib.h", "copy" ]
lua_copy_inc_luaconf=[ "../luaconf.h", "include/luaconf.h", "copy" ]
lua_copy_inc_lua=[ "../lua.h", "include/lua.h", "copy" ]
lua_copy_inc_ltm=[ "../ltm.h", "include/ltm.h", "copy" ]
lua_copy_inc_ltests=[ "../ltests.h", "include/ltests.h", "copy" ]
lua_copy_inc_ltable=[ "../ltable.h", "include/ltable.h", "copy" ]
lua_copy_inc_lstring=[ "../lstring.h", "include/lstring.h", "copy" ]
lua_copy_inc_lstate=[ "../lstate.h", "include/lstate.h", "copy" ]
lua_copy_inc_lprefix=[ "../lprefix.h", "include/lprefix.h", "copy" ]
lua_copy_inc_lparser=[ "../lparser.h", "include/lparser.h", "copy" ]
lua_copy_inc_lopnames=[ "../lopnames.h", "include/lopnames.h", "copy" ]
lua_copy_inc_lopcodes=[ "../lopcodes.h", "include/lopcodes.h", "copy" ]
lua_copy_inc_lobject=[ "../lobject.h", "include/lobject.h", "copy" ]
lua_copy_inc_lmem=[ "../lmem.h", "include/lmem.h", "copy" ]
lua_copy_inc_llimits=[ "../llimits.h", "include/llimits.h", "copy" ]
lua_copy_inc_llex=[ "../llex.h", "include/llex.h", "copy" ]
lua_copy_inc_ljumptab=[ "../ljumptab.h", "include/ljumptab.h", "copy" ]
lua_copy_inc_lgc=[ "../lgc.h", "include/lgc.h", "copy" ]
lua_copy_inc_lfunc=[ "../lfunc.h", "include/lfunc.h", "copy" ]
lua_copy_inc_ldo=[ "../ldo.h", "include/ldo.h", "copy" ]
lua_copy_inc_ldebug=[ "../ldebug.h", "include/ldebug.h", "copy" ]
lua_copy_inc_lctype=[ "../lctype.h", "include/lctype.h", "copy" ]
lua_copy_inc_lcode=[ "../lcode.h", "include/lcode.h", "copy" ]
lua_copy_inc_lauxlib=[ "../lauxlib.h", "include/lauxlib.h", "copy" ]
lua_copy_inc_lapi=[ "../lapi.h", "include/lapi.h", "copy" ]

[windows-gnu-post-build-sync]
lo_bin_rel=[ "build/temp/release-windows-gnu/lua-gnu.lib", "build/${version}/lua-gnu.lib", "copy" ]
lo_bin_deb=[ "build/temp/debug-windows-gnu/lua-gnud.lib", "build/${version}/lua-gnud.lib", "copy" ]
lo_include=[ "include", "build/${version}/include", "copy" ]
lo_license=[ "LICENSE", "build/${version}/LICENSE", "copy" ]

[linux-sync]
lua_copy_src_onelua=[ "../onelua.c", "src/onelua.c", "copy" ]
lua_copy_src_lzio=[ "../lzio.c", "src/lzio.c", "copy" ]
lua_copy_src_lvm=[ "../lvm.c", "src/lvm.c", "copy" ]
lua_copy_src_lutf8lib=[ "../lutf8lib.c", "src/lutf8lib.c", "copy" ]
lua_copy_src_lundump=[ "../lundump.c", "src/lundump.c", "copy" ]
lua_copy_src_lua=[ "../lua.c", "src/lua.c", "copy" ]
lua_copy_src_ltm=[ "../ltm.c", "src/ltm.c", "copy" ]
lua_copy_src_ltests=[ "../ltests.c", "src/ltests.c", "copy" ]
lua_copy_src_ltablib=[ "../ltablib.c", "src/ltablib.c", "copy" ]
lua_copy_src_ltable=[ "../ltable.c", "src/ltable.c", "copy" ]
lua_copy_src_lstrlib=[ "../lstrlib.c", "src/lstrlib.c", "copy" ]
lua_copy_src_lstring=[ "../lstring.c", "src/lstring.c", "copy" ]
lua_copy_src_lstate=[ "../lstate.c", "src/lstate.c", "copy" ]
lua_copy_src_lparser=[ "../lparser.c", "src/lparser.c", "copy" ]
lua_copy_src_loslib=[ "../loslib.c", "src/loslib.c", "copy" ]
lua_copy_src_lopcodes=[ "../lopcodes.c", "src/lopcodes.c", "copy" ]
lua_copy_src_lobject=[ "../lobject.c", "src/lobject.c", "copy" ]
lua_copy_src_loadlib=[ "../loadlib.c", "src/loadlib.c", "copy" ]
lua_copy_src_lmem=[ "../lmem.c", "src/lmem.c", "copy" ]
lua_copy_src_lmathlib=[ "../lmathlib.c", "src/lmathlib.c", "copy" ]
lua_copy_src_llex=[ "../llex.c", "src/llex.c", "copy" ]
lua_copy_src_liolib=[ "../liolib.c", "src/liolib.c", "copy" ]
lua_copy_src_linit=[ "../linit.c", "src/linit.c", "copy" ]
lua_copy_src_lgc=[ "../lgc.c", "src/lgc.c", "copy" ]
lua_copy_src_lfunc=[ "../lfunc.c", "src/lfunc.c", "copy" ]
lua_copy_src_ldump=[ "../ldump.c", "src/ldump.c", "copy" ]
lua_copy_src_ldo=[ "../ldo.c", "src/ldo.c", "copy" ]
lua_copy_src_ldebug=[ "../ldebug.c", "src/ldebug.c", "copy" ]
lua_copy_src_ldblib=[ "../ldblib.c", "src/ldblib.c", "copy" ]
lua_copy_src_lctype=[ "../lctype.c", "src/lctype.c", "copy" ]
lua_copy_src_lcorolib=[ "../lcorolib.c", "src/lcorolib.c", "copy" ]
lua_copy_src_lcode=[ "../lcode.c", "src/lcode.c", "copy" ]
lua_copy_src_lbaselib=[ "../lbaselib.c", "src/lbaselib.c", "copy" ]
lua_copy_src_lauxlib=[ "../lauxlib.c", "src/lauxlib.c", "copy" ]
lua_copy_src_lapi=[ "../lapi.c", "src/lapi.c", "copy" ]
lua_copy_inc_lzio=[ "../lzio.h", "include/lzio.h", "copy" ]
lua_copy_inc_lvm=[ "../lvm.h", "include/lvm.h", "copy" ]
lua_copy_inc_lundump=[ "../lundump.h", "include/lundump.h", "copy" ]
lua_copy_inc_lualib=[ "../lualib.h", "include/lualib.h", "copy" ]
lua_copy_inc_luaconf=[ "../luaconf.h", "include/luaconf.h", "copy" ]
lua_copy_inc_lua=[ "../lua.h", "include/lua.h", "copy" ]
lua_copy_inc_ltm=[ "../ltm.h", "include/ltm.h", "copy" ]
lua_copy_inc_ltests=[ "../ltests.h", "include/ltests.h", "copy" ]
lua_copy_inc_ltable=[ "../ltable.h", "include/ltable.h", "copy" ]
lua_copy_inc_lstring=[ "../lstring.h", "include/lstring.h", "copy" ]
lua_copy_inc_lstate=[ "../lstate.h", "include/lstate.h", "copy" ]
lua_copy_inc_lprefix=[ "../lprefix.h", "include/lprefix.h", "copy" ]
lua_copy_inc_lparser=[ "../lparser.h", "include/lparser.h", "copy" ]
lua_copy_inc_lopnames=[ "../lopnames.h", "include/lopnames.h", "copy" ]
lua_copy_inc_lopcodes=[ "../lopcodes.h", "include/lopcodes.h", "copy" ]
lua_copy_inc_lobject=[ "../lobject.h", "include/lobject.h", "copy" ]
lua_copy_inc_lmem=[ "../lmem.h", "include/lmem.h", "copy" ]
lua_copy_inc_llimits=[ "../llimits.h", "include/llimits.h", "copy" ]
lua_copy_inc_llex=[ "../llex.h", "include/llex.h", "copy" ]
lua_copy_inc_ljumptab=[ "../ljumptab.h", "include/ljumptab.h", "copy" ]
lua_copy_inc_lgc=[ "../lgc.h", "include/lgc.h", "copy" ]
lua_copy_inc_lfunc=[ "../lfunc.h", "include/lfunc.h", "copy" ]
lua_copy_inc_ldo=[ "../ldo.h", "include/ldo.h", "copy" ]
lua_copy_inc_ldebug=[ "../ldebug.h", "include/ldebug.h", "copy" ]
lua_copy_inc_lctype=[ "../lctype.h", "include/lctype.h", "copy" ]
lua_copy_inc_lcode=[ "../lcode.h", "include/lcode.h", "copy" ]
lua_copy_inc_lauxlib=[ "../lauxlib.h", "include/lauxlib.h", "copy" ]
lua_copy_inc_lapi=[ "../lapi.h", "include/lapi.h", "copy" ]

[linux-post-build-sync]
lo_bin_rel=[ "build/temp/release-linux/liblua.a", "build/${version}/liblua.a", "copy" ]
lo_bin_deb=[ "build/temp/debug-linux/libluad.a", "build/${version}/libluad.a", "copy" ]
lo_include=[ "include", "build/${version}/include", "copy" ]
lo_license=[ "LICENSE", "build/${version}/LICENSE", "copy" ]

